package inventory

import "errors"

var (
	ErrNegativeDemand            = errors.New("demand cannot be negative")
	ErrNegativeLeadTime          = errors.New("lead time cannot be negative")
	ErrNegativeSafetyStock       = errors.New("safety stock cannot be negative")
	ErrNegativeOrderingCost      = errors.New("ordering cost cannot be negative")
	ErrInvalidOrderingCost       = errors.New("ordering cost must be greater than zero")
	ErrInvalidHoldingCost        = errors.New("holding cost must be greater than zero")
	ErrNegativeOrderQuantity     = errors.New("order quantity cannot be negative")
	ErrNegativeReorderPoint      = errors.New("reorder point cannot be negative")
	ErrInvalidServiceLevel       = errors.New("service level must be between 0 and 1 exclusive")
	ErrNegativeStandardDeviation = errors.New("standard deviation cannot be negative")
	ErrNegativeExpectedDemand    = errors.New("expected demand cannot be negative")
	ErrInvalidPolicySummaryInput = errors.New("invalid policy summary input")
	ErrNegativeReviewPeriod      = errors.New("review period cannot be negative")
	ErrNonFiniteInput            = errors.New("input values must be finite (not NaN or Inf)")

	ErrInvalidProductionRate         = errors.New("production rate must be greater than demand rate")
	ErrInvalidUnderageCost           = errors.New("underage cost must be greater than zero")
	ErrInvalidOverageCost            = errors.New("overage cost must be greater than zero")
	ErrInvalidFillRate               = errors.New("fill rate must be between 0 and 1 exclusive")
	ErrEmptyDiscountTiers            = errors.New("discount tiers must contain at least one tier")
	ErrInvalidDiscountTiers          = errors.New("discount tiers must be sorted by strictly ascending minimum quantity, starting above zero, with positive, non-increasing unit prices")
	ErrInvalidOrderQuantity          = errors.New("order quantity must be greater than zero")
	ErrInvalidStandardDeviation      = errors.New("standard deviation must be greater than zero")
	ErrNegativeAverageInventoryValue = errors.New("average inventory value cannot be negative")
	ErrInvalidAverageInventoryValue  = errors.New("average inventory value must be greater than zero")
	ErrNegativeCOGS                  = errors.New("cost of goods sold cannot be negative")
	ErrInvalidCOGS                   = errors.New("cost of goods sold must be greater than zero")
	ErrInvalidDaysInPeriod           = errors.New("days in period must be greater than zero")
	ErrInvalidAverageInventoryCost   = errors.New("average inventory cost must be greater than zero")
	ErrFillRateNotAchievable         = errors.New("target fill rate is not achievable within supported precision for the given order quantity and demand variability")
)
